eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true
#心跳检查，自我保护模式，开发环境关闭
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka